name: "Deploy yo AWS S3"
description: "Deploy a statis website via AWS S3."
inputs:
  bucket:
    description: "The S3 bucket name."
    required: true
  region:
    description: "The S3 region."
    required: false
    default: "us-east-1"
  dist-folder:
    description: "The folder containing the deployable files."
    required: true
outputs:
  website-url:
    description: "The url for the hosted website."
    # DO NOT DEFINE OUTPUT HERE. WE DO THAT FROM INSIDE OF main.js FILE
runs:
  using: node24
  # name of the file that should be executred for this custom action
  main: main.js
