name: "Deploy to AWS S3 with Python"
description: "Deploy a statis website via AWS S3."
inputs:
  bucket:
    description: "The S3 bucket name."
    required: true
  region:
    description: "The S3 region."
    required: false
    default: "us-east-1"
  dist-folder:
    description: "The folder containing the deployable files."
    required: true
outputs:
  website-url:
    description: "The url for the hosted website."
runs:
  using: "docker"
  image: "Dockerfile"
